In [1]:
#check numpy version
import numpy as np
np.__version__

'2.3.0'

In [2]:
lst=[1, 2, 3, 4, 5]
arr1 = np.array(lst)  #coversion of list to numpy array
print(type(arr1))  #check type of arr
print(arr1)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
arr1 = np.arange(1, 10)  # create an array with start, stop and step
print(arr1) # 1 to n-1 print honge

[1 2 3 4 5 6 7 8 9]


In [4]:
arr3=np.ones(5)  #create an array of ones
print(arr3)
arr3

[1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1.])

In [5]:
arr3=np.zeros(5)        #create an array of zeros
arr3   

array([0., 0., 0., 0., 0.])

In [6]:
arr5=np.linspace(0, 10, 20)  #create an array with evenly spaced numbers over a specified interval
print(arr5)  # 1 to 10 with 5 evenly spaced numbers

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [7]:
##conversion of 1d to 2d array
arr6=np.arange(1,31).reshape(5,6)   #reshape the array to 5 rows and 6 columns
print(arr6)  # 1 to 30 in 5 rows and 6 columns
arr6

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [8]:
arr7=np.random.randint(1,100,10) #random integers between 1 and 100, 10 elements
print(arr7)  # 10 random integers between 1 and 100
arr7

[65 48 80 52 61 91 51 84 48 63]


array([65, 48, 80, 52, 61, 91, 51, 84, 48, 63], dtype=int32)

In [9]:
arr7=np.random.random(10)  #random floats between 0 and 1, 10 elements
print(arr7)  # 10 random floats between 0 and 1

[0.33133006 0.81471678 0.69856775 0.90917521 0.60611112 0.23400782
 0.00459377 0.78658995 0.37468884 0.64488631]


In [10]:
arr8=np.array([10,6])
arr8.shape #shape of the array
arr8.dtype #data type of the array
arr8.size #number of elements in the array
arr8.ndim  #number of dimensions

1

In [11]:
arr8.ravel()  #flatten the array to 1d
arr8.flatten()  #flatten the array to 1d, same as ravel

array([10,  6])

In [12]:
arr8=np.arange(1,31).reshape(5,6)  
print(arr8.shape)  #shape of the array
arr9=arr8.T.shape  #transpose the array and get the shape
print(arr9)  #shape of the transposed array

(5, 6)
(6, 5)


In [13]:
arr8=np.array([5,6])
arr9=arr8.T.shape
print(arr9)  #shape of the transposed array, should be same as original since it's 1d

(2,)


In [14]:
#indexing and slicing in 2d array
##2d array---[rowstart:rowend:rowskip, colstart:colend:colskip]
arr8=np.arange(1,31).reshape(5,6)
arr8

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [15]:
arr8=np.arange(1,31).reshape(5,6)
arr8[2:2,3:5]  #selecting specific rows and columns
arr8[2:4,3:5]  #selecting rows 2 to 3 and columns 3 to 4

array([[16, 17],
       [22, 23]])

In [16]:
type(arr8[2:4,3:5])  #check type of the sliced array


numpy.ndarray

In [17]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  #2D array
print(arr2)
arr2[1:2, 1:3]  #selecting specific rows and columns
arr2[1:2, 1:3].shape  #shape of the sliced

[[1 2 3]
 [4 5 6]]


(1, 2)

In [18]:
arr10=np.arange(27).reshape(3,3,3)  #create a 2D array with 2 rows and 5 columns
arr10

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [19]:
#3d array
arr10 = np.arange(225).reshape(3, 15, 5)  # create a 3D array with shape (10, 10, 10)
print(arr10.shape)  # shape of the 3D array
arr10

(3, 15, 5)


array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [20]:
arr10=np.ones((3, 3, 3))  # create a 3D array of ones with shape (3, 3, 3)
arr10

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
##slicing in 3d array
##syntax--
# [tablestart:tableend:tableskip, rowstart:rowend:rowskip, colstart:colend:colskip]
# Select all tables, rows 1 to 3, columns 2 to 3
arr10[:, 1:4, 2:4]  # selecting specific tables, rows and columns

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [22]:
np.max(arr8) #maximum value in the array
np.min(arr8) #minimum value in the array

np.int64(1)

In [23]:
np.sum(arr8)  #sum of all elements in the array

np.int64(465)

In [24]:
np.mean(arr8)  #mean of all elements in the array

np.float64(15.5)

In [25]:
np.median(arr8)  #median of all elements in the array

np.float64(15.5)

In [26]:
np.std(arr8)  #standard deviation of all elements in the array

np.float64(8.65544144839919)

In [27]:
arr8.sort()
print(arr8)  #sorted array

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [28]:
arr11=np.array([2,5,1,6,3,4])
arr1.argsort()  #returns the indices that would sort the array
print(arr11.argsort())  #indices that would sort the array  ,array sorted through indices.

[2 0 4 5 1 3]


In [29]:
arr11 + 2 #adding 2 to each element of the array
arr11 * 2  #multiplying each element of the array by 2
arr11 ** 2  #squaring each element of the array                         

array([ 4, 25,  1, 36,  9, 16])

In [30]:
arr11=np.array([2,5,1,6,3,4])
arr12=np.array([])